const express = require('express');
const axios = require('axios');
const User = require('../models/User');

const router = express.Router();

// 本地職業提取函數
function extractProfessionFromText(text) {
  const lowerText = text.toLowerCase();
  
  // 職業關鍵詞映射（包含創意職業）
  const professionKeywords = {
    // 傳統職業
    '醫生': ['醫生', '醫師', '大夫', '醫', 'doctor', 'physician'],
    '護士': ['護士', '護理師', 'nurse'],
    '教師': ['教師', '老師', '教授', '講師', 'teacher', 'professor'],
    '律師': ['律師', 'lawyer', 'attorney'],
    '工程師': ['工程師', 'engineer'],
    '設計師': ['設計師', 'designer'],
    '會計師': ['會計師', 'accountant'],
    '建築師': ['建築師', 'architect'],
    '警察': ['警察', 'police', 'officer'],
    '消防員': ['消防員', 'firefighter'],
    '軍人': ['軍人', 'soldier', 'military'],
    '飛行員': ['飛行員', 'pilot'],
    '廚師': ['廚師', 'chef', 'cook'],
    '攝影師': ['攝影師', 'photographer'],
    '藝術家': ['藝術家', 'artist'],
    '音樂家': ['音樂家', 'musician'],
    '演員': ['演員', 'actor', 'actress'],
    '運動員': ['運動員', 'athlete'],
    '科學家': ['科學家', 'scientist'],
    '記者': ['記者', 'journalist', 'reporter'],
    
    // 創意和夢想職業
    '太空人': ['太空人', '宇航員', 'astronaut', 'spaceman'],
    '特首': ['特首', '行政長官', 'chief executive', 'ceo'],
    '總統': ['總統', 'president'],
    '總理': ['總理', 'prime minister'],
    '市長': ['市長', 'mayor'],
    '議員': ['議員', 'legislator', 'member of parliament'],
    '法官': ['法官', 'judge'],
    '檢察官': ['檢察官', 'prosecutor'],
    '外交官': ['外交官', 'diplomat'],
    '大使': ['大使', 'ambassador'],
    '幼兒老師': ['幼兒老師', '幼稚園老師', 'kindergarten teacher', 'preschool teacher'],
    '遊戲設計師': ['遊戲設計師', 'game designer', 'game developer'],
    '動畫師': ['動畫師', 'animator', 'animation artist'],
    '電影導演': ['電影導演', '導演', 'film director', 'movie director'],
    '漫畫家': ['漫畫家', 'comic artist', 'manga artist', 'cartoonist'],
    '電競選手': ['電競選手', '電競', 'esports player', 'gamer', 'pro gamer'],
    'YouTuber': ['youtuber', 'youtube', '網紅', 'content creator', 'vlogger'],
    '程式設計師': ['程式設計師', 'programmer', 'developer', 'software engineer'],
    '創業家': ['創業家', '企業家', 'entrepreneur', 'startup founder'],
    '海洋生物學家': ['海洋生物學家', 'marine biologist', 'ocean scientist'],
    '考古學家': ['考古學家', 'archaeologist'],
    '獸醫': ['獸醫', 'veterinarian', 'vet'],
    '心理學家': ['心理學家', 'psychologist'],
    '環境科學家': ['環境科學家', 'environmental scientist'],
    '機器人工程師': ['機器人工程師', 'robotics engineer', 'robot engineer'],
    'AI研究員': ['AI研究員', '人工智能研究員', 'AI researcher', 'artificial intelligence researcher'],
    '時裝設計師': ['時裝設計師', 'fashion designer'],
    '珠寶設計師': ['珠寶設計師', 'jewelry designer'],
    '咖啡師': ['咖啡師', 'barista'],
    '魔術師': ['魔術師', 'magician'],
    '小丑': ['小丑', 'clown'],
    '雜技演員': ['雜技演員', 'acrobat'],
    '馬戲團演員': ['馬戲團演員', 'circus performer'],
    '馴獸師': ['馴獸師', 'animal trainer'],
    '探險家': ['探險家', 'explorer', 'adventurer'],
    '冒險家': ['冒險家', 'adventurer'],
    '海盜': ['海盜', 'pirate'],
    '海軍': ['海軍', 'navy', 'sailor'],
    '空軍': ['空軍', 'air force', 'pilot'],
    '陸軍': ['陸軍', 'army', 'soldier'],
    '特種部隊': ['特種部隊', 'special forces', 'commando'],
    '間諜': ['間諜', 'spy', 'secret agent'],
    '偵探': ['偵探', 'detective', 'private investigator'],
    '私家偵探': ['私家偵探', 'private detective'],
    '賞金獵人': ['賞金獵人', 'bounty hunter'],
    '牛仔': ['牛仔', 'cowboy'],
    '騎士': ['騎士', 'knight'],
    '武士': ['武士', 'samurai'],
    '忍者': ['忍者', 'ninja'],
    '海盜王': ['海盜王', 'pirate king'],
    '海賊王': ['海賊王', 'pirate king'],
    '超級英雄': ['超級英雄', 'superhero'],
    '英雄': ['英雄', 'hero'],
    '救世主': ['救世主', 'savior', 'messiah'],
    '先知': ['先知', 'prophet'],
    '巫師': ['巫師', 'wizard', 'witch'],
    '魔法師': ['魔法師', 'magician', 'wizard'],
    '煉金術士': ['煉金術士', 'alchemist'],
    '占卜師': ['占卜師', 'fortune teller'],
    '算命師': ['算命師', 'fortune teller'],
    '風水師': ['風水師', 'feng shui master'],
    '道士': ['道士', 'taoist priest'],
    '和尚': ['和尚', 'monk'],
    '牧師': ['牧師', 'priest'],
    '神父': ['神父', 'priest'],
    '修女': ['修女', 'nun'],
    '傳教士': ['傳教士', 'missionary'],
    '聖人': ['聖人', 'saint'],
    '天使': ['天使', 'angel'],
    '惡魔': ['惡魔', 'demon'],
    '吸血鬼': ['吸血鬼', 'vampire'],
    '狼人': ['狼人', 'werewolf'],
    '殭屍': ['殭屍', 'zombie'],
    '外星人': ['外星人', 'alien'],
    '機器人': ['機器人', 'robot'],
    '賽博朋克': ['賽博朋克', 'cyberpunk'],
    '未來戰士': ['未來戰士', 'future warrior'],
    '時空旅行者': ['時空旅行者', 'time traveler'],
    '平行宇宙探險家': ['平行宇宙探險家', 'parallel universe explorer'],
    '星際海盜': ['星際海盜', 'space pirate'],
    '銀河系守護者': ['銀河系守護者', 'galaxy guardian'],
    '宇宙探險家': ['宇宙探險家', 'space explorer'],
    '星際戰士': ['星際戰士', 'space warrior'],
    '銀河系皇帝': ['銀河系皇帝', 'galaxy emperor'],
    '星際女王': ['星際女王', 'space queen'],
    '宇宙之王': ['宇宙之王', 'king of the universe'],
    '時空守護者': ['時空守護者', 'time guardian'],
    '維度旅行者': ['維度旅行者', 'dimension traveler'],
    '量子物理學家': ['量子物理學家', 'quantum physicist'],
    '弦理論學家': ['弦理論學家', 'string theorist'],
    '黑洞研究員': ['黑洞研究員', 'black hole researcher'],
    '暗物質探測員': ['暗物質探測員', 'dark matter detector'],
    '蟲洞工程師': ['蟲洞工程師', 'wormhole engineer'],
    '時空工程師': ['時空工程師', 'spacetime engineer'],
    '平行宇宙研究員': ['平行宇宙研究員', 'parallel universe researcher'],
    '多維度科學家': ['多維度科學家', 'multidimensional scientist'],
    '宇宙學家': ['宇宙學家', 'cosmologist'],
    '天體物理學家': ['天體物理學家', 'astrophysicist'],
    '行星科學家': ['行星科學家', 'planetary scientist'],
    '恆星天文學家': ['恆星天文學家', 'stellar astronomer'],
    '銀河系天文學家': ['銀河系天文學家', 'galactic astronomer'],
    '宇宙射線研究員': ['宇宙射線研究員', 'cosmic ray researcher'],
    '中微子物理學家': ['中微子物理學家', 'neutrino physicist'],
    '暗能量研究員': ['暗能量研究員', 'dark energy researcher'],
    '引力波探測員': ['引力波探測員', 'gravitational wave detector'],
    '超弦理論學家': ['超弦理論學家', 'superstring theorist'],
    'M理論學家': ['M理論學家', 'M-theory physicist'],
    '全息原理研究員': ['全息原理研究員', 'holographic principle researcher'],
    '量子糾纏專家': ['量子糾纏專家', 'quantum entanglement expert'],
    '量子計算機科學家': ['量子計算機科學家', 'quantum computer scientist'],
    '量子密碼學家': ['量子密碼學家', 'quantum cryptographer'],
    '量子通訊工程師': ['量子通訊工程師', 'quantum communication engineer'],
    '量子感測器專家': ['量子感測器專家', 'quantum sensor expert'],
    '量子成像專家': ['量子成像專家', 'quantum imaging expert'],
    '量子雷達工程師': ['量子雷達工程師', 'quantum radar engineer'],
    '量子衛星工程師': ['量子衛星工程師', 'quantum satellite engineer'],
    '量子網路工程師': ['量子網路工程師', 'quantum network engineer'],
    '量子人工智慧專家': ['量子人工智慧專家', 'quantum AI expert'],
    '量子機器學習專家': ['量子機器學習專家', 'quantum machine learning expert'],
    '量子神經網路專家': ['量子神經網路專家', 'quantum neural network expert'],
    '量子深度學習專家': ['量子深度學習專家', 'quantum deep learning expert'],
    '量子強化學習專家': ['量子強化學習專家', 'quantum reinforcement learning expert'],
    '量子自然語言處理專家': ['量子自然語言處理專家', 'quantum NLP expert'],
    '量子電腦視覺專家': ['量子電腦視覺專家', 'quantum computer vision expert'],
    '量子語音識別專家': ['量子語音識別專家', 'quantum speech recognition expert'],
    '量子翻譯專家': ['量子翻譯專家', 'quantum translation expert'],
    '量子推薦系統專家': ['量子推薦系統專家', 'quantum recommendation system expert'],
    '量子搜尋引擎專家': ['量子搜尋引擎專家', 'quantum search engine expert'],
    '量子社交網路專家': ['量子社交網路專家', 'quantum social network expert'],
    '量子遊戲開發者': ['量子遊戲開發者', 'quantum game developer'],
    '量子虛擬實境專家': ['量子虛擬實境專家', 'quantum VR expert'],
    '量子擴增實境專家': ['量子擴增實境專家', 'quantum AR expert'],
    '量子混合實境專家': ['量子混合實境專家', 'quantum MR expert'],
    '量子腦機介面專家': ['量子腦機介面專家', 'quantum brain-computer interface expert'],
    '量子神經科學家': ['量子神經科學家', 'quantum neuroscientist'],
    '量子認知科學家': ['量子認知科學家', 'quantum cognitive scientist'],
    '量子心理學家': ['量子心理學家', 'quantum psychologist'],
    '量子哲學家': ['量子哲學家', 'quantum philosopher'],
    '量子倫理學家': ['量子倫理學家', 'quantum ethicist'],
    '量子社會學家': ['量子社會學家', 'quantum sociologist'],
    '量子經濟學家': ['量子經濟學家', 'quantum economist'],
    '量子政治學家': ['量子政治學家', 'quantum political scientist'],
    '量子歷史學家': ['量子歷史學家', 'quantum historian'],
    '量子考古學家': ['量子考古學家', 'quantum archaeologist'],
    '量子人類學家': ['量子人類學家', 'quantum anthropologist'],
    '量子語言學家': ['量子語言學家', 'quantum linguist'],
    '量子文學家': ['量子文學家', 'quantum literary scholar'],
    '量子藝術史學家': ['量子藝術史學家', 'quantum art historian'],
    '量子音樂學家': ['量子音樂學家', 'quantum musicologist'],
    '量子電影學家': ['量子電影學家', 'quantum film scholar'],
    '量子戲劇學家': ['量子戲劇學家', 'quantum theater scholar'],
    '量子舞蹈學家': ['量子舞蹈學家', 'quantum dance scholar'],
    '量子建築學家': ['量子建築學家', 'quantum architect'],
    '量子設計師': ['量子設計師', 'quantum designer'],
    '量子藝術家': ['量子藝術家', 'quantum artist'],
    '量子音樂家': ['量子音樂家', 'quantum musician'],
    '量子作家': ['量子作家', 'quantum writer'],
    '量子詩人': ['量子詩人', 'quantum poet'],
    '量子編劇': ['量子編劇', 'quantum screenwriter'],
    '量子導演': ['量子導演', 'quantum director'],
    '量子演員': ['量子演員', 'quantum actor'],
    '量子歌手': ['量子歌手', 'quantum singer'],
    '量子舞者': ['量子舞者', 'quantum dancer'],
    '量子畫家': ['量子畫家', 'quantum painter'],
    '量子雕塑家': ['量子雕塑家', 'quantum sculptor'],
    '量子攝影師': ['量子攝影師', 'quantum photographer'],
    '量子電影攝影師': ['量子電影攝影師', 'quantum cinematographer'],
    '量子音效師': ['量子音效師', 'quantum sound engineer'],
    '量子混音師': ['量子混音師', 'quantum mixing engineer'],
    '量子母帶工程師': ['量子母帶工程師', 'quantum mastering engineer'],
    '量子錄音師': ['量子錄音師', 'quantum recording engineer'],
    '量子調音師': ['量子調音師', 'quantum tuner'],
    '量子樂器技師': ['量子樂器技師', 'quantum instrument technician'],
    '量子鋼琴調音師': ['量子鋼琴調音師', 'quantum piano tuner'],
    '量子小提琴製琴師': ['量子小提琴製琴師', 'quantum violin maker'],
    '量子吉他製琴師': ['量子吉他製琴師', 'quantum guitar maker'],
    '量子鼓手': ['量子鼓手', 'quantum drummer'],
    '量子貝斯手': ['量子貝斯手', 'quantum bassist'],
    '量子吉他手': ['量子吉他手', 'quantum guitarist'],
    '量子鍵盤手': ['量子鍵盤手', 'quantum keyboardist'],
    '量子主唱': ['量子主唱', 'quantum vocalist'],
    '量子和聲': ['量子和聲', 'quantum backup singer'],
    '量子合唱團': ['量子合唱團', 'quantum choir'],
    '量子管弦樂團': ['量子管弦樂團', 'quantum orchestra'],
    '量子交響樂團': ['量子交響樂團', 'quantum symphony'],
    '量子室內樂團': ['量子室內樂團', 'quantum chamber ensemble'],
    '量子爵士樂團': ['量子爵士樂團', 'quantum jazz band'],
    '量子搖滾樂團': ['量子搖滾樂團', 'quantum rock band'],
    '量子流行樂團': ['量子流行樂團', 'quantum pop band'],
    '量子民謠樂團': ['量子民謠樂團', 'quantum folk band'],
    '量子古典樂團': ['量子古典樂團', 'quantum classical ensemble'],
    '量子電子樂團': ['量子電子樂團', 'quantum electronic band'],
    '量子嘻哈樂團': ['量子嘻哈樂團', 'quantum hip hop group'],
    '量子饒舌歌手': ['量子饒舌歌手', 'quantum rapper'],
    '量子DJ': ['量子DJ', 'quantum disc jockey'],
    '量子MC': ['量子MC', 'quantum master of ceremonies'],
    '量子編舞家': ['量子編舞家', 'quantum choreographer'],
    '量子舞蹈老師': ['量子舞蹈老師', 'quantum dance teacher'],
    '量子瑜珈老師': ['量子瑜珈老師', 'quantum yoga teacher'],
    '量子健身教練': ['量子健身教練', 'quantum personal trainer'],
    '量子游泳教練': ['量子游泳教練', 'quantum swimming coach'],
    '量子網球教練': ['量子網球教練', 'quantum tennis coach'],
    '量子籃球教練': ['量子籃球教練', 'quantum basketball coach'],
    '量子足球教練': ['量子足球教練', 'quantum soccer coach'],
    '量子棒球教練': ['量子棒球教練', 'quantum baseball coach'],
    '量子排球教練': ['量子排球教練', 'quantum volleyball coach'],
    '量子羽球教練': ['量子羽球教練', 'quantum badminton coach'],
    '量子桌球教練': ['量子桌球教練', 'quantum table tennis coach'],
    '量子高爾夫教練': ['量子高爾夫教練', 'quantum golf coach'],
    '量子滑雪教練': ['量子滑雪教練', 'quantum ski instructor'],
    '量子衝浪教練': ['量子衝浪教練', 'quantum surf instructor'],
    '量子潛水教練': ['量子潛水教練', 'quantum diving instructor'],
    '量子攀岩教練': ['量子攀岩教練', 'quantum rock climbing instructor'],
    '量子登山嚮導': ['量子登山嚮導', 'quantum mountain guide'],
    '量子旅遊領隊': ['量子旅遊領隊', 'quantum tour leader'],
    '量子導遊': ['量子導遊', 'quantum tour guide'],
    '量子解說員': ['量子解說員', 'quantum interpreter'],
    '量子博物館員': ['量子博物館員', 'quantum museum curator'],
    '量子圖書館員': ['量子圖書館員', 'quantum librarian'],
    '量子檔案管理員': ['量子檔案管理員', 'quantum archivist'],
    '量子資料管理員': ['量子資料管理員', 'quantum data manager'],
    '量子系統管理員': ['量子系統管理員', 'quantum system administrator'],
    '量子網路管理員': ['量子網路管理員', 'quantum network administrator'],
    '量子資料庫管理員': ['量子資料庫管理員', 'quantum database administrator'],
    '量子伺服器管理員': ['量子伺服器管理員', 'quantum server administrator'],
    '量子安全工程師': ['量子安全工程師', 'quantum security engineer'],
    '量子資安工程師': ['量子資安工程師', 'quantum cybersecurity engineer'],
    '量子網路安全工程師': ['量子網路安全工程師', 'quantum network security engineer'],
    '量子滲透測試工程師': ['量子滲透測試工程師', 'quantum penetration tester'],
    '量子資安顧問': ['量子資安顧問', 'quantum cybersecurity consultant'],
    '量子資安分析師': ['量子資安分析師', 'quantum cybersecurity analyst'],
    '量子資安管理師': ['量子資安管理師', 'quantum cybersecurity manager'],
    '量子資安稽核師': ['量子資安稽核師', 'quantum cybersecurity auditor'],
    '量子資安法規專家': ['量子資安法規專家', 'quantum cybersecurity compliance expert'],
    '量子資安教育訓練師': ['量子資安教育訓練師', 'quantum cybersecurity trainer'],
    '量子資安事件處理師': ['量子資安事件處理師', 'quantum cybersecurity incident responder'],
    '量子資安應變工程師': ['量子資安應變工程師', 'quantum cybersecurity response engineer'],
    '量子資安復原工程師': ['量子資安復原工程師', 'quantum cybersecurity recovery engineer'],
    '量子資安風險管理師': ['量子資安風險管理師', 'quantum cybersecurity risk manager'],
    '量子資安政策制定師': ['量子資安政策制定師', 'quantum cybersecurity policy maker'],
    '量子資安標準制定師': ['量子資安標準制定師', 'quantum cybersecurity standard maker'],
    '量子資安認證工程師': ['量子資安認證工程師', 'quantum cybersecurity certification engineer'],
    '量子資安合規工程師': ['量子資安合規工程師', 'quantum cybersecurity compliance engineer'],
    '量子資安治理專家': ['量子資安治理專家', 'quantum cybersecurity governance expert'],
    '量子資安策略顧問': ['量子資安策略顧問', 'quantum cybersecurity strategy consultant'],
    '量子資安總監': ['量子資安總監', 'quantum chief cybersecurity officer'],
    '量子資安長': ['量子資安長', 'quantum chief information security officer'],
    '量子資訊長': ['量子資訊長', 'quantum chief information officer'],
    '量子技術長': ['量子技術長', 'quantum chief technology officer'],
    '量子營運長': ['量子營運長', 'quantum chief operating officer'],
    '量子財務長': ['量子財務長', 'quantum chief financial officer'],
    '量子人資長': ['量子人資長', 'quantum chief human resources officer'],
    '量子行銷長': ['量子行銷長', 'quantum chief marketing officer'],
    '量子業務長': ['量子業務長', 'quantum chief sales officer'],
    '量子法務長': ['量子法務長', 'quantum chief legal officer'],
    '量子公關長': ['量子公關長', 'quantum chief public relations officer'],
    '量子永續長': ['量子永續長', 'quantum chief sustainability officer'],
    '量子創新長': ['量子創新長', 'quantum chief innovation officer'],
    '量子數位長': ['量子數位長', 'quantum chief digital officer'],
    '量子轉型長': ['量子轉型長', 'quantum chief transformation officer'],
    '量子策略長': ['量子策略長', 'quantum chief strategy officer'],
    '量子顧問長': ['量子顧問長', 'quantum chief advisor'],
    '量子總經理': ['量子總經理', 'quantum general manager'],
    '量子副總經理': ['量子副總經理', 'quantum deputy general manager'],
    '量子協理': ['量子協理', 'quantum assistant manager'],
    '量子經理': ['量子經理', 'quantum manager'],
    '量子副理': ['量子副理', 'quantum deputy manager'],
    '量子主任': ['量子主任', 'quantum director'],
    '量子組長': ['量子組長', 'quantum team leader'],
    '量子課長': ['量子課長', 'quantum section chief'],
    '量子股長': ['量子股長', 'quantum unit chief'],
    '量子專員': ['量子專員', 'quantum specialist'],
    '量子助理': ['量子助理', 'quantum assistant'],
    '量子實習生': ['量子實習生', 'quantum intern'],
    '量子工讀生': ['量子工讀生', 'quantum part-time worker'],
    '量子兼職': ['量子兼職', 'quantum part-time'],
    '量子全職': ['量子全職', 'quantum full-time'],
    '量子自由工作者': ['量子自由工作者', 'quantum freelancer'],
    '量子接案者': ['量子接案者', 'quantum contractor'],
    '量子創業家': ['量子創業家', 'quantum entrepreneur'],
    '量子投資人': ['量子投資人', 'quantum investor'],
    '量子股東': ['量子股東', 'quantum shareholder'],
    '量子董事': ['量子董事', 'quantum director'],
    '量子監事': ['量子監事', 'quantum supervisor'],
    '量子顧問': ['量子顧問', 'quantum consultant'],
    '量子委員': ['量子委員', 'quantum committee member'],
    '量子代表': ['量子代表', 'quantum representative'],
    '量子大使': ['量子大使', 'quantum ambassador'],
    '量子特使': ['量子特使', 'quantum special envoy'],
    '量子專員': ['量子專員', 'quantum specialist'],
    '量子專案': ['量子專案', 'quantum project'],
    '量子計畫': ['量子計畫', 'quantum plan'],
    '量子專案經理': ['量子專案經理', 'quantum project manager'],
    '量子產品經理': ['量子產品經理', 'quantum product manager'],
    '量子專案助理': ['量子專案助理', 'quantum project assistant'],
    '量子產品助理': ['量子產品助理', 'quantum product assistant'],
    '量子業務助理': ['量子業務助理', 'quantum sales assistant'],
    '量子行政助理': ['量子行政助理', 'quantum administrative assistant'],
    '量子人資助理': ['量子人資助理', 'quantum HR assistant'],
    '量子財務助理': ['量子財務助理', 'quantum finance assistant'],
    '量子會計助理': ['量子會計助理', 'quantum accounting assistant'],
    '量子法務助理': ['量子法務助理', 'quantum legal assistant'],
    '量子公關助理': ['量子公關助理', 'quantum PR assistant'],
    '量子行銷助理': ['量子行銷助理', 'quantum marketing assistant'],
    '量子企劃助理': ['量子企劃助理', 'quantum planning assistant'],
    '量子設計助理': ['量子設計助理', 'quantum design assistant'],
    '量子工程助理': ['量子工程助理', 'quantum engineering assistant'],
    '量子技術助理': ['量子技術助理', 'quantum technical assistant'],
    '量子研究助理': ['量子研究助理', 'quantum research assistant'],
    '量子教學助理': ['量子教學助理', 'quantum teaching assistant'],
    '量子研究員': ['量子研究員', 'quantum researcher'],
    '量子助理研究員': ['量子助理研究員', 'quantum assistant researcher'],
    '量子副研究員': ['量子副研究員', 'quantum associate researcher'],
    '量子研究員': ['量子研究員', 'quantum researcher'],
    '量子資深研究員': ['量子資深研究員', 'quantum senior researcher'],
    '量子首席研究員': ['量子首席研究員', 'quantum principal researcher'],
    '量子研究總監': ['量子研究總監', 'quantum research director'],
    '量子研究長': ['量子研究長', 'quantum chief research officer'],
    '量子研發長': ['量子研發長', 'quantum chief R&D officer'],
    '量子研發經理': ['量子研發經理', 'quantum R&D manager'],
    '量子研發工程師': ['量子研發工程師', 'quantum R&D engineer'],
    '量子研發助理': ['量子研發助理', 'quantum R&D assistant'],
    '量子研發專員': ['量子研發專員', 'quantum R&D specialist'],
    '量子研發主管': ['量子研發主管', 'quantum R&D supervisor'],
    '量子研發總監': ['量子研發總監', 'quantum R&D director'],
    '量子研發副總': ['量子研發副總', 'quantum R&D vice president'],
    '量子研發總經理': ['量子研發總經理', 'quantum R&D general manager'],
    '量子研發長': ['量子研發長', 'quantum chief R&D officer'],
    '量子創新長': ['量子創新長', 'quantum chief innovation officer'],
    '量子創新經理': ['量子創新經理', 'quantum innovation manager'],
    '量子創新工程師': ['量子創新工程師', 'quantum innovation engineer'],
    '量子創新助理': ['量子創新助理', 'quantum innovation assistant'],
    '量子創新專員': ['量子創新專員', 'quantum innovation specialist'],
    '量子創新主管': ['量子創新主管', 'quantum innovation supervisor'],
    '量子創新總監': ['量子創新總監', 'quantum innovation director'],
    '量子創新副總': ['量子創新副總', 'quantum innovation vice president'],
    '量子創新總經理': ['量子創新總經理', 'quantum innovation general manager'],
    '量子創新長': ['量子創新長', 'quantum chief innovation officer'],
    '量子數位長': ['量子數位長', 'quantum chief digital officer'],
    '量子數位經理': ['量子數位經理', 'quantum digital manager'],
    '量子數位工程師': ['量子數位工程師', 'quantum digital engineer'],
    '量子數位助理': ['量子數位助理', 'quantum digital assistant'],
    '量子數位專員': ['量子數位專員', 'quantum digital specialist'],
    '量子數位主管': ['量子數位主管', 'quantum digital supervisor'],
    '量子數位總監': ['量子數位總監', 'quantum digital director'],
    '量子數位副總': ['量子數位副總', 'quantum digital vice president'],
    '量子數位總經理': ['量子數位總經理', 'quantum digital general manager'],
    '量子數位長': ['量子數位長', 'quantum chief digital officer'],
    '量子轉型長': ['量子轉型長', 'quantum chief transformation officer'],
    '量子轉型經理': ['量子轉型經理', 'quantum transformation manager'],
    '量子轉型工程師': ['量子轉型工程師', 'quantum transformation engineer'],
    '量子轉型助理': ['量子轉型助理', 'quantum transformation assistant'],
    '量子轉型專員': ['量子轉型專員', 'quantum transformation specialist'],
    '量子轉型主管': ['量子轉型主管', 'quantum transformation supervisor'],
    '量子轉型總監': ['量子轉型總監', 'quantum transformation director'],
    '量子轉型副總': ['量子轉型副總', 'quantum transformation vice president'],
    '量子轉型總經理': ['量子轉型總經理', 'quantum transformation general manager'],
    '量子轉型長': ['量子轉型長', 'quantum chief transformation officer'],
    '量子策略長': ['量子策略長', 'quantum chief strategy officer'],
    '量子策略經理': ['量子策略經理', 'quantum strategy manager'],
    '量子策略工程師': ['量子策略工程師', 'quantum strategy engineer'],
    '量子策略助理': ['量子策略助理', 'quantum strategy assistant'],
    '量子策略專員': ['量子策略專員', 'quantum strategy specialist'],
    '量子策略主管': ['量子策略主管', 'quantum strategy supervisor'],
    '量子策略總監': ['量子策略總監', 'quantum strategy director'],
    '量子策略副總': ['量子策略副總', 'quantum strategy vice president'],
    '量子策略總經理': ['量子策略總經理', 'quantum strategy general manager'],
    '量子策略長': ['量子策略長', 'quantum chief strategy officer'],
    '量子顧問長': ['量子顧問長', 'quantum chief advisor'],
    '量子顧問經理': ['量子顧問經理', 'quantum advisor manager'],
    '量子顧問工程師': ['量子顧問工程師', 'quantum advisor engineer'],
    '量子顧問助理': ['量子顧問助理', 'quantum advisor assistant'],
    '量子顧問專員': ['量子顧問專員', 'quantum advisor specialist'],
    '量子顧問主管': ['量子顧問主管', 'quantum advisor supervisor'],
    '量子顧問總監': ['量子顧問總監', 'quantum advisor director'],
    '量子顧問副總': ['量子顧問副總', 'quantum advisor vice president'],
    '量子顧問總經理': ['量子顧問總經理', 'quantum advisor general manager'],
    '量子顧問長': ['量子顧問長', 'quantum chief advisor'],
    
    // 其他職業（保持原有）
    '護理師': ['護理師', 'nurse'],
    '營養師': ['營養師', 'nutritionist'],
    '心理師': ['心理師', 'psychologist'],
    '社工': ['社工', 'social worker'],
    '翻譯': ['翻譯', 'translator'],
    '導遊': ['導遊', 'tour guide'],
    '教授': ['教授', 'professor'],
    '學者': ['學者', 'scholar'],
    '專家': ['專家', 'expert'],
    '顧問': ['顧問', 'consultant'],
    '分析師': ['分析師', 'analyst'],
    '經理': ['經理', 'manager'],
    '主管': ['主管', 'supervisor'],
    '老闆': ['老闆', 'boss', 'owner'],
    '企業家': ['企業家', 'entrepreneur'],
    '研究員': ['研究員', 'researcher'],
    '作家': ['作家', 'writer', 'author'],
    '導演': ['導演', 'director'],
    '主持人': ['主持人', 'host', 'presenter'],
    '主播': ['主播', 'anchor'],
    '教練': ['教練', 'coach'],
    '司機': ['司機', 'driver'],
    '服務員': ['服務員', 'waiter', 'waitress'],
    '銷售員': ['銷售員', 'salesperson'],
    '技師': ['技師', 'technician'],
    '維修員': ['維修員', 'repairman'],
    '清潔員': ['清潔員', 'cleaner'],
    '保全': ['保全', 'security'],
    '警衛': ['警衛', 'guard'],
    '園丁': ['園丁', 'gardener'],
    '農夫': ['農夫', 'farmer'],
    '漁夫': ['漁夫', 'fisherman'],
    '礦工': ['礦工', 'miner'],
    '工人': ['工人', 'worker'],
    '技工': ['技工', 'mechanic'],
    '電工': ['電工', 'electrician'],
    '水電工': ['水電工', 'plumber'],
    '木工': ['木工', 'carpenter'],
    '油漆工': ['油漆工', 'painter'],
    '泥水工': ['泥水工', 'mason'],
    '鐵工': ['鐵工', 'blacksmith'],
    '焊接工': ['焊接工', 'welder'],
    '機械工': ['機械工', 'machinist'],
    '汽車技師': ['汽車技師', 'auto mechanic'],
    '機車技師': ['機車技師', 'motorcycle mechanic'],
    '美容師': ['美容師', 'beautician'],
    '理髮師': ['理髮師', 'barber', 'hairdresser'],
    '化妝師': ['化妝師', 'makeup artist'],
    '造型師': ['造型師', 'stylist'],
    '服裝設計師': ['服裝設計師', 'fashion designer'],
    '珠寶設計師': ['珠寶設計師', 'jewelry designer'],
    '室內設計師': ['室內設計師', 'interior designer'],
    '景觀設計師': ['景觀設計師', 'landscape designer'],
    '平面設計師': ['平面設計師', 'graphic designer'],
    '網頁設計師': ['網頁設計師', 'web designer'],
    'UI設計師': ['UI設計師', 'UI designer'],
    'UX設計師': ['UX設計師', 'UX designer'],
    '遊戲設計師': ['遊戲設計師', 'game designer'],
    '動畫師': ['動畫師', 'animator'],
    '特效師': ['特效師', 'special effects artist'],
    '剪輯師': ['剪輯師', 'editor'],
    '音效師': ['音效師', 'sound engineer'],
    '調音師': ['調音師', 'tuner'],
    '錄音師': ['錄音師', 'recording engineer'],
    '混音師': ['混音師', 'mixer'],
    '製作人': ['製作人', 'producer'],
    '編劇': ['編劇', 'screenwriter'],
    '製片': ['製片', 'producer'],
    '場記': ['場記', 'script supervisor'],
    '燈光師': ['燈光師', 'lighting technician'],
    '攝影助理': ['攝影助理', 'camera assistant'],
    '化妝助理': ['化妝助理', 'makeup assistant'],
    '服裝助理': ['服裝助理', 'costume assistant'],
    '道具師': ['道具師', 'prop master'],
    '佈景師': ['佈景師', 'set designer'],
    '特效化妝師': ['特效化妝師', 'special effects makeup artist'],
    '替身演員': ['替身演員', 'stunt double'],
    '配音員': ['配音員', 'voice actor'],
    '聲優': ['聲優', 'voice actor'],
    '模特兒': ['模特兒', 'model'],
    '舞者': ['舞者', 'dancer'],
    '歌手': ['歌手', 'singer'],
    '樂手': ['樂手', 'musician'],
    '指揮家': ['指揮家', 'conductor'],
    '作曲家': ['作曲家', 'composer'],
    '編曲家': ['編曲家', 'arranger'],
    '音樂製作人': ['音樂製作人', 'music producer'],
    '錄音工程師': ['錄音工程師', 'recording engineer'],
    '混音工程師': ['混音工程師', 'mixing engineer'],
    '母帶工程師': ['母帶工程師', 'mastering engineer'],
    '音響師': ['音響師', 'sound engineer'],
    '樂器技師': ['樂器技師', 'instrument technician'],
    '鋼琴調音師': ['鋼琴調音師', 'piano tuner'],
    '小提琴製琴師': ['小提琴製琴師', 'violin maker'],
    '吉他製琴師': ['吉他製琴師', 'guitar maker'],
    '鼓手': ['鼓手', 'drummer'],
    '貝斯手': ['貝斯手', 'bassist'],
    '吉他手': ['吉他手', 'guitarist'],
    '鍵盤手': ['鍵盤手', 'keyboardist'],
    '主唱': ['主唱', 'vocalist'],
    '和聲': ['和聲', 'backup singer'],
    '合唱團': ['合唱團', 'choir'],
    '管弦樂團': ['管弦樂團', 'orchestra'],
    '交響樂團': ['交響樂團', 'symphony'],
    '室內樂團': ['室內樂團', 'chamber ensemble'],
    '爵士樂團': ['爵士樂團', 'jazz band'],
    '搖滾樂團': ['搖滾樂團', 'rock band'],
    '流行樂團': ['流行樂團', 'pop band'],
    '民謠樂團': ['民謠樂團', 'folk band'],
    '古典樂團': ['古典樂團', 'classical ensemble'],
    '電子樂團': ['電子樂團', 'electronic band'],
    '嘻哈樂團': ['嘻哈樂團', 'hip hop group'],
    '饒舌歌手': ['饒舌歌手', 'rapper'],
    'DJ': ['DJ', 'disc jockey'],
    'MC': ['MC', 'master of ceremonies'],
    '編舞家': ['編舞家', 'choreographer'],
    '舞蹈老師': ['舞蹈老師', 'dance teacher'],
    '瑜珈老師': ['瑜珈老師', 'yoga teacher'],
    '健身教練': ['健身教練', 'personal trainer'],
    '游泳教練': ['游泳教練', 'swimming coach'],
    '網球教練': ['網球教練', 'tennis coach'],
    '籃球教練': ['籃球教練', 'basketball coach'],
    '足球教練': ['足球教練', 'soccer coach'],
    '棒球教練': ['棒球教練', 'baseball coach'],
    '排球教練': ['排球教練', 'volleyball coach'],
    '羽球教練': ['羽球教練', 'badminton coach'],
    '桌球教練': ['桌球教練', 'table tennis coach'],
    '高爾夫教練': ['高爾夫教練', 'golf coach'],
    '滑雪教練': ['滑雪教練', 'ski instructor'],
    '衝浪教練': ['衝浪教練', 'surf instructor'],
    '潛水教練': ['潛水教練', 'diving instructor'],
    '攀岩教練': ['攀岩教練', 'rock climbing instructor'],
    '登山嚮導': ['登山嚮導', 'mountain guide'],
    '旅遊領隊': ['旅遊領隊', 'tour leader'],
    '導遊': ['導遊', 'tour guide'],
    '解說員': ['解說員', 'interpreter'],
    '博物館員': ['博物館員', 'museum curator'],
    '圖書館員': ['圖書館員', 'librarian'],
    '檔案管理員': ['檔案管理員', 'archivist'],
    '資料管理員': ['資料管理員', 'data manager'],
    '系統管理員': ['系統管理員', 'system administrator'],
    '網路管理員': ['網路管理員', 'network administrator'],
    '資料庫管理員': ['資料庫管理員', 'database administrator'],
    '伺服器管理員': ['伺服器管理員', 'server administrator'],
    '安全工程師': ['安全工程師', 'security engineer'],
    '資安工程師': ['資安工程師', 'cybersecurity engineer'],
    '網路安全工程師': ['網路安全工程師', 'network security engineer'],
    '滲透測試工程師': ['滲透測試工程師', 'penetration tester'],
    '資安顧問': ['資安顧問', 'cybersecurity consultant'],
    '資安分析師': ['資安分析師', 'cybersecurity analyst'],
    '資安管理師': ['資安管理師', 'cybersecurity manager'],
    '資安稽核師': ['資安稽核師', 'cybersecurity auditor'],
    '資安法規專家': ['資安法規專家', 'cybersecurity compliance expert'],
    '資安教育訓練師': ['資安教育訓練師', 'cybersecurity trainer'],
    '資安事件處理師': ['資安事件處理師', 'cybersecurity incident responder'],
    '資安應變工程師': ['資安應變工程師', 'cybersecurity response engineer'],
    '資安復原工程師': ['資安復原工程師', 'cybersecurity recovery engineer'],
    '資安風險管理師': ['資安風險管理師', 'cybersecurity risk manager'],
    '資安政策制定師': ['資安政策制定師', 'cybersecurity policy maker'],
    '資安標準制定師': ['資安標準制定師', 'cybersecurity standards developer'],
    '資安認證工程師': ['資安認證工程師', 'cybersecurity certification engineer'],
    '資安合規工程師': ['資安合規工程師', 'cybersecurity compliance engineer'],
    '資安治理專家': ['資安治理專家', 'cybersecurity governance expert'],
    '資安策略顧問': ['資安策略顧問', 'cybersecurity strategy consultant'],
    '資安總監': ['資安總監', 'cybersecurity director'],
    '資安長': ['資安長', 'chief security officer'],
    '資訊長': ['資訊長', 'chief information officer'],
    '技術長': ['技術長', 'chief technology officer'],
    '營運長': ['營運長', 'chief operating officer'],
    '財務長': ['財務長', 'chief financial officer'],
    '人資長': ['人資長', 'chief human resources officer'],
    '行銷長': ['行銷長', 'chief marketing officer'],
    '業務長': ['業務長', 'chief business officer'],
    '法務長': ['法務長', 'chief legal officer'],
    '公關長': ['公關長', 'chief public relations officer'],
    '永續長': ['永續長', 'chief sustainability officer'],
    '創新長': ['創新長', 'chief innovation officer'],
    '數位長': ['數位長', 'chief digital officer'],
    '轉型長': ['轉型長', 'chief transformation officer'],
    '策略長': ['策略長', 'chief strategy officer'],
    '顧問長': ['顧問長', 'chief advisor'],
    '總經理': ['總經理', 'general manager'],
    '副總經理': ['副總經理', 'deputy general manager'],
    '協理': ['協理', 'assistant manager'],
    '經理': ['經理', 'manager'],
    '副理': ['副理', 'deputy manager'],
    '主任': ['主任', 'director'],
    '組長': ['組長', 'team leader'],
    '課長': ['課長', 'section chief'],
    '股長': ['股長', 'unit chief'],
    '專員': ['專員', 'specialist'],
    '助理': ['助理', 'assistant'],
    '實習生': ['實習生', 'intern'],
    '工讀生': ['工讀生', 'part-time student'],
    '兼職': ['兼職', 'part-time'],
    '全職': ['全職', 'full-time'],
    '自由工作者': ['自由工作者', 'freelancer'],
    '接案者': ['接案者', 'contractor'],
    '創業家': ['創業家', 'entrepreneur'],
    '投資人': ['投資人', 'investor'],
    '股東': ['股東', 'shareholder'],
    '董事': ['董事', 'director'],
    '監事': ['監事', 'supervisor'],
    '顧問': ['顧問', 'consultant'],
    '委員': ['委員', 'committee member'],
    '代表': ['代表', 'representative'],
    '大使': ['大使', 'ambassador'],
    '特使': ['特使', 'special envoy'],
    '專員': ['專員', 'specialist'],
    '專案': ['專案', 'project'],
    '計畫': ['計畫', 'plan'],
    '專案經理': ['專案經理', 'project manager'],
    '產品經理': ['產品經理', 'product manager'],
    '專案助理': ['專案助理', 'project assistant'],
    '產品助理': ['產品助理', 'product assistant'],
    '業務助理': ['業務助理', 'business assistant'],
    '行政助理': ['行政助理', 'administrative assistant'],
    '人資助理': ['人資助理', 'HR assistant'],
    '財務助理': ['財務助理', 'finance assistant'],
    '會計助理': ['會計助理', 'accounting assistant'],
    '法務助理': ['法務助理', 'legal assistant'],
    '公關助理': ['公關助理', 'public relations assistant'],
    '行銷助理': ['行銷助理', 'marketing assistant'],
    '企劃助理': ['企劃助理', 'planning assistant'],
    '設計助理': ['設計助理', 'design assistant'],
    '工程助理': ['工程助理', 'engineering assistant'],
    '技術助理': ['技術助理', 'technical assistant'],
    '研究助理': ['研究助理', 'research assistant'],
    '教學助理': ['教學助理', 'teaching assistant'],
    '研究員': ['研究員', 'researcher'],
    '助理研究員': ['助理研究員', 'assistant researcher'],
    '副研究員': ['副研究員', 'associate researcher'],
    '資深研究員': ['資深研究員', 'senior researcher'],
    '首席研究員': ['首席研究員', 'principal researcher'],
    '研究總監': ['研究總監', 'research director'],
    '研究長': ['研究長', 'chief research officer'],
    '研發長': ['研發長', 'chief R&D officer'],
    '研發經理': ['研發經理', 'R&D manager'],
    '研發工程師': ['研發工程師', 'R&D engineer'],
    '研發助理': ['研發助理', 'R&D assistant'],
    '研發專員': ['研發專員', 'R&D specialist'],
    '研發主管': ['研發主管', 'R&D supervisor'],
    '研發總監': ['研發總監', 'R&D director'],
    '研發副總': ['研發副總', 'deputy R&D vice president'],
    '研發總經理': ['研發總經理', 'R&D general manager'],
    '創新長': ['創新長', 'chief innovation officer'],
    '創新經理': ['創新經理', 'innovation manager'],
    '創新工程師': ['創新工程師', 'innovation engineer'],
    '創新助理': ['創新助理', 'innovation assistant'],
    '創新專員': ['創新專員', 'innovation specialist'],
    '創新主管': ['創新主管', 'innovation supervisor'],
    '創新總監': ['創新總監', 'innovation director'],
    '創新副總': ['創新副總', 'deputy innovation vice president'],
    '創新總經理': ['創新總經理', 'innovation general manager'],
    '數位長': ['數位長', 'chief digital officer'],
    '數位經理': ['數位經理', 'digital manager'],
    '數位工程師': ['數位工程師', 'digital engineer'],
    '數位助理': ['數位助理', 'digital assistant'],
    '數位專員': ['數位專員', 'digital specialist'],
    '數位主管': ['數位主管', 'digital supervisor'],
    '數位總監': ['數位總監', 'digital director'],
    '數位副總': ['數位副總', 'deputy digital vice president'],
    '數位總經理': ['數位總經理', 'digital general manager'],
    '轉型長': ['轉型長', 'chief transformation officer'],
    '轉型經理': ['轉型經理', 'transformation manager'],
    '轉型工程師': ['轉型工程師', 'transformation engineer'],
    '轉型助理': ['轉型助理', 'transformation assistant'],
    '轉型專員': ['轉型專員', 'transformation specialist'],
    '轉型主管': ['轉型主管', 'transformation supervisor'],
    '轉型總監': ['轉型總監', 'transformation director'],
    '轉型副總': ['轉型副總', 'deputy transformation vice president'],
    '轉型總經理': ['轉型總經理', 'transformation general manager'],
    '策略長': ['策略長', 'chief strategy officer'],
    '策略經理': ['策略經理', 'strategy manager'],
    '策略工程師': ['策略工程師', 'strategy engineer'],
    '策略助理': ['策略助理', 'strategy assistant'],
    '策略專員': ['策略專員', 'strategy specialist'],
    '策略主管': ['策略主管', 'strategy supervisor'],
    '策略總監': ['策略總監', 'strategy director'],
    '策略副總': ['策略副總', 'deputy strategy vice president'],
    '策略總經理': ['策略總經理', 'strategy general manager'],
    '顧問長': ['顧問長', 'chief advisor'],
    '顧問經理': ['顧問經理', 'advisor manager'],
    '顧問工程師': ['顧問工程師', 'advisor engineer'],
    '顧問助理': ['顧問助理', 'advisor assistant'],
    '顧問專員': ['顧問專員', 'advisor specialist'],
    '顧問主管': ['顧問主管', 'advisor supervisor'],
    '顧問總監': ['顧問總監', 'advisor director'],
    '顧問副總': ['顧問副總', 'deputy advisor vice president'],
    '顧問總經理': ['顧問總經理', 'advisor general manager']
  };

  // 檢查文字中是否包含職業關鍵詞
  for (const [profession, keywords] of Object.entries(professionKeywords)) {
    for (const keyword of keywords) {
      if (lowerText.includes(keyword.toLowerCase())) {
        return profession;
      }
    }
  }
  
  // 檢查新添加的創意職業
  const creativeProfessions = {
    '太空人': ['太空人', '宇航員', 'astronaut', 'spaceman'],
    '特首': ['特首', '行政長官', 'chief executive', 'ceo'],
    '總統': ['總統', 'president'],
    '總理': ['總理', 'prime minister'],
    '市長': ['市長', 'mayor'],
    '議員': ['議員', 'legislator', 'member of parliament'],
    '法官': ['法官', 'judge'],
    '檢察官': ['檢察官', 'prosecutor'],
    '外交官': ['外交官', 'diplomat'],
    '大使': ['大使', 'ambassador'],
    '海盜王': ['海盜王', 'pirate king'],
    '海賊王': ['海賊王', 'pirate king'],
    '超級英雄': ['超級英雄', 'superhero'],
    '英雄': ['英雄', 'hero'],
    '救世主': ['救世主', 'savior', 'messiah'],
    '宇宙之王': ['宇宙之王', 'king of the universe'],
    '時空旅行者': ['時空旅行者', 'time traveler'],
    '量子物理學家': ['量子物理學家', 'quantum physicist'],
    '星際戰士': ['星際戰士', 'space warrior'],
    '銀河系皇帝': ['銀河系皇帝', 'galaxy emperor'],
    '星際女王': ['星際女王', 'space queen'],
    '時空守護者': ['時空守護者', 'time guardian'],
    '維度旅行者': ['維度旅行者', 'dimension traveler'],
    '平行宇宙探險家': ['平行宇宙探險家', 'parallel universe explorer'],
    '星際海盜': ['星際海盜', 'space pirate'],
    '銀河系守護者': ['銀河系守護者', 'galaxy guardian'],
    '宇宙探險家': ['宇宙探險家', 'space explorer'],
    '黑洞研究員': ['黑洞研究員', 'black hole researcher'],
    '暗物質探測員': ['暗物質探測員', 'dark matter detector'],
    '蟲洞工程師': ['蟲洞工程師', 'wormhole engineer'],
    '時空工程師': ['時空工程師', 'spacetime engineer'],
    '平行宇宙研究員': ['平行宇宙研究員', 'parallel universe researcher'],
    '多維度科學家': ['多維度科學家', 'multidimensional scientist'],
    '宇宙學家': ['宇宙學家', 'cosmologist'],
    '天體物理學家': ['天體物理學家', 'astrophysicist'],
    '行星科學家': ['行星科學家', 'planetary scientist'],
    '恆星天文學家': ['恆星天文學家', 'stellar astronomer'],
    '銀河系天文學家': ['銀河系天文學家', 'galactic astronomer'],
    '宇宙射線研究員': ['宇宙射線研究員', 'cosmic ray researcher'],
    '中微子物理學家': ['中微子物理學家', 'neutrino physicist'],
    '暗能量研究員': ['暗能量研究員', 'dark energy researcher'],
    '引力波探測員': ['引力波探測員', 'gravitational wave detector'],
    '超弦理論學家': ['超弦理論學家', 'superstring theorist'],
    'M理論學家': ['M理論學家', 'M-theory physicist'],
    '全息原理研究員': ['全息原理研究員', 'holographic principle researcher'],
    '量子糾纏專家': ['量子糾纏專家', 'quantum entanglement expert'],
    '量子計算機科學家': ['量子計算機科學家', 'quantum computer scientist'],
    '量子密碼學家': ['量子密碼學家', 'quantum cryptographer'],
    '量子通訊工程師': ['量子通訊工程師', 'quantum communication engineer'],
    '量子感測器專家': ['量子感測器專家', 'quantum sensor expert'],
    '量子成像專家': ['量子成像專家', 'quantum imaging expert'],
    '量子雷達工程師': ['量子雷達工程師', 'quantum radar engineer'],
    '量子衛星工程師': ['量子衛星工程師', 'quantum satellite engineer'],
    '量子網路工程師': ['量子網路工程師', 'quantum network engineer'],
    '量子人工智慧專家': ['量子人工智慧專家', 'quantum AI expert'],
    '量子機器學習專家': ['量子機器學習專家', 'quantum machine learning expert'],
    '量子神經網路專家': ['量子神經網路專家', 'quantum neural network expert'],
    '量子深度學習專家': ['量子深度學習專家', 'quantum deep learning expert'],
    '量子強化學習專家': ['量子強化學習專家', 'quantum reinforcement learning expert'],
    '量子自然語言處理專家': ['量子自然語言處理專家', 'quantum NLP expert'],
    '量子電腦視覺專家': ['量子電腦視覺專家', 'quantum computer vision expert'],
    '量子語音識別專家': ['量子語音識別專家', 'quantum speech recognition expert'],
    '量子翻譯專家': ['量子翻譯專家', 'quantum translation expert'],
    '量子推薦系統專家': ['量子推薦系統專家', 'quantum recommendation system expert'],
    '量子搜尋引擎專家': ['量子搜尋引擎專家', 'quantum search engine expert'],
    '量子社交網路專家': ['量子社交網路專家', 'quantum social network expert'],
    '量子遊戲開發者': ['量子遊戲開發者', 'quantum game developer'],
    '量子虛擬實境專家': ['量子虛擬實境專家', 'quantum VR expert'],
    '量子擴增實境專家': ['量子擴增實境專家', 'quantum AR expert'],
    '量子混合實境專家': ['量子混合實境專家', 'quantum MR expert'],
    '量子腦機介面專家': ['量子腦機介面專家', 'quantum brain-computer interface expert'],
    '量子神經科學家': ['量子神經科學家', 'quantum neuroscientist'],
    '量子認知科學家': ['量子認知科學家', 'quantum cognitive scientist'],
    '量子心理學家': ['量子心理學家', 'quantum psychologist'],
    '量子哲學家': ['量子哲學家', 'quantum philosopher'],
    '量子倫理學家': ['量子倫理學家', 'quantum ethicist'],
    '量子社會學家': ['量子社會學家', 'quantum sociologist'],
    '量子經濟學家': ['量子經濟學家', 'quantum economist'],
    '量子政治學家': ['量子政治學家', 'quantum political scientist'],
    '量子歷史學家': ['量子歷史學家', 'quantum historian'],
    '量子考古學家': ['量子考古學家', 'quantum archaeologist'],
    '量子人類學家': ['量子人類學家', 'quantum anthropologist'],
    '量子語言學家': ['量子語言學家', 'quantum linguist'],
    '量子文學家': ['量子文學家', 'quantum literary scholar'],
    '量子藝術史學家': ['量子藝術史學家', 'quantum art historian'],
    '量子音樂學家': ['量子音樂學家', 'quantum musicologist'],
    '量子電影學家': ['量子電影學家', 'quantum film scholar'],
    '量子戲劇學家': ['量子戲劇學家', 'quantum theater scholar'],
    '量子舞蹈學家': ['量子舞蹈學家', 'quantum dance scholar'],
    '量子建築學家': ['量子建築學家', 'quantum architect'],
    '量子設計師': ['量子設計師', 'quantum designer'],
    '量子藝術家': ['量子藝術家', 'quantum artist'],
    '量子音樂家': ['量子音樂家', 'quantum musician'],
    '量子作家': ['量子作家', 'quantum writer'],
    '量子詩人': ['量子詩人', 'quantum poet'],
    '量子編劇': ['量子編劇', 'quantum screenwriter'],
    '量子導演': ['量子導演', 'quantum director'],
    '量子演員': ['量子演員', 'quantum actor'],
    '量子歌手': ['量子歌手', 'quantum singer'],
    '量子舞者': ['量子舞者', 'quantum dancer'],
    '量子畫家': ['量子畫家', 'quantum painter'],
    '量子雕塑家': ['量子雕塑家', 'quantum sculptor'],
    '量子攝影師': ['量子攝影師', 'quantum photographer'],
    '量子電影攝影師': ['量子電影攝影師', 'quantum cinematographer'],
    '量子音效師': ['量子音效師', 'quantum sound engineer'],
    '量子混音師': ['量子混音師', 'quantum mixing engineer'],
    '量子母帶工程師': ['量子母帶工程師', 'quantum mastering engineer'],
    '量子錄音師': ['量子錄音師', 'quantum recording engineer'],
    '量子調音師': ['量子調音師', 'quantum tuner'],
    '量子樂器技師': ['量子樂器技師', 'quantum instrument technician'],
    '量子鋼琴調音師': ['量子鋼琴調音師', 'quantum piano tuner'],
    '量子小提琴製琴師': ['量子小提琴製琴師', 'quantum violin maker'],
    '量子吉他製琴師': ['量子吉他製琴師', 'quantum guitar maker'],
    '量子鼓手': ['量子鼓手', 'quantum drummer'],
    '量子貝斯手': ['量子貝斯手', 'quantum bassist'],
    '量子吉他手': ['量子吉他手', 'quantum guitarist'],
    '量子鍵盤手': ['量子鍵盤手', 'quantum keyboardist'],
    '量子主唱': ['量子主唱', 'quantum vocalist'],
    '量子和聲': ['量子和聲', 'quantum backup singer'],
    '量子合唱團': ['量子合唱團', 'quantum choir'],
    '量子管弦樂團': ['量子管弦樂團', 'quantum orchestra'],
    '量子交響樂團': ['量子交響樂團', 'quantum symphony'],
    '量子室內樂團': ['量子室內樂團', 'quantum chamber ensemble'],
    '量子爵士樂團': ['量子爵士樂團', 'quantum jazz band'],
    '量子搖滾樂團': ['量子搖滾樂團', 'quantum rock band'],
    '量子流行樂團': ['量子流行樂團', 'quantum pop band'],
    '量子民謠樂團': ['量子民謠樂團', 'quantum folk band'],
    '量子古典樂團': ['量子古典樂團', 'quantum classical ensemble'],
    '量子電子樂團': ['量子電子樂團', 'quantum electronic band'],
    '量子嘻哈樂團': ['量子嘻哈樂團', 'quantum hip hop group'],
    '量子饒舌歌手': ['量子饒舌歌手', 'quantum rapper'],
    '量子DJ': ['量子DJ', 'quantum disc jockey'],
    '量子MC': ['量子MC', 'quantum master of ceremonies'],
    '量子編舞家': ['量子編舞家', 'quantum choreographer'],
    '量子舞蹈老師': ['量子舞蹈老師', 'quantum dance teacher'],
    '量子瑜珈老師': ['量子瑜珈老師', 'quantum yoga teacher'],
    '量子健身教練': ['量子健身教練', 'quantum personal trainer'],
    '量子游泳教練': ['量子游泳教練', 'quantum swimming coach'],
    '量子網球教練': ['量子網球教練', 'quantum tennis coach'],
    '量子籃球教練': ['量子籃球教練', 'quantum basketball coach'],
    '量子足球教練': ['量子足球教練', 'quantum soccer coach'],
    '量子棒球教練': ['量子棒球教練', 'quantum baseball coach'],
    '量子排球教練': ['量子排球教練', 'quantum volleyball coach'],
    '量子羽球教練': ['量子羽球教練', 'quantum badminton coach'],
    '量子桌球教練': ['量子桌球教練', 'quantum table tennis coach'],
    '量子高爾夫教練': ['量子高爾夫教練', 'quantum golf coach'],
    '量子滑雪教練': ['量子滑雪教練', 'quantum ski instructor'],
    '量子衝浪教練': ['量子衝浪教練', 'quantum surf instructor'],
    '量子潛水教練': ['量子潛水教練', 'quantum diving instructor'],
    '量子攀岩教練': ['量子攀岩教練', 'quantum rock climbing instructor'],
    '量子登山嚮導': ['量子登山嚮導', 'quantum mountain guide'],
    '量子旅遊領隊': ['量子旅遊領隊', 'quantum tour leader'],
    '量子導遊': ['量子導遊', 'quantum tour guide'],
    '量子解說員': ['量子解說員', 'quantum interpreter'],
    '量子博物館員': ['量子博物館員', 'quantum museum curator'],
    '量子圖書館員': ['量子圖書館員', 'quantum librarian'],
    '量子檔案管理員': ['量子檔案管理員', 'quantum archivist'],
    '量子資料管理員': ['量子資料管理員', 'quantum data manager'],
    '量子系統管理員': ['量子系統管理員', 'quantum system administrator'],
    '量子網路管理員': ['量子網路管理員', 'quantum network administrator'],
    '量子資料庫管理員': ['量子資料庫管理員', 'quantum database administrator'],
    '量子伺服器管理員': ['量子伺服器管理員', 'quantum server administrator'],
    '量子安全工程師': ['量子安全工程師', 'quantum security engineer'],
    '量子資安工程師': ['量子資安工程師', 'quantum cybersecurity engineer'],
    '量子網路安全工程師': ['量子網路安全工程師', 'quantum network security engineer'],
    '量子滲透測試工程師': ['量子滲透測試工程師', 'quantum penetration tester'],
    '量子資安顧問': ['量子資安顧問', 'quantum cybersecurity consultant'],
    '量子資安分析師': ['量子資安分析師', 'quantum cybersecurity analyst'],
    '量子資安管理師': ['量子資安管理師', 'quantum cybersecurity manager'],
    '量子資安稽核師': ['量子資安稽核師', 'quantum cybersecurity auditor'],
    '量子資安法規專家': ['量子資安法規專家', 'quantum cybersecurity compliance expert'],
    '量子資安教育訓練師': ['量子資安教育訓練師', 'quantum cybersecurity trainer'],
    '量子資安事件處理師': ['量子資安事件處理師', 'quantum cybersecurity incident responder'],
    '量子資安應變工程師': ['量子資安應變工程師', 'quantum cybersecurity response engineer'],
    '量子資安復原工程師': ['量子資安復原工程師', 'quantum cybersecurity recovery engineer'],
    '量子資安風險管理師': ['量子資安風險管理師', 'quantum cybersecurity risk manager'],
    '量子資安政策制定師': ['量子資安政策制定師', 'quantum cybersecurity policy maker'],
    '量子資安標準制定師': ['量子資安標準制定師', 'quantum cybersecurity standard maker'],
    '量子資安認證工程師': ['量子資安認證工程師', 'quantum cybersecurity certification engineer'],
    '量子資安合規工程師': ['量子資安合規工程師', 'quantum cybersecurity compliance engineer'],
    '量子資安治理專家': ['量子資安治理專家', 'quantum cybersecurity governance expert'],
    '量子資安策略顧問': ['量子資安策略顧問', 'quantum cybersecurity strategy consultant'],
    '量子資安總監': ['量子資安總監', 'quantum chief cybersecurity officer'],
    '量子資安長': ['量子資安長', 'quantum chief information security officer'],
    '量子資訊長': ['量子資訊長', 'quantum chief information officer'],
    '量子技術長': ['量子技術長', 'quantum chief technology officer'],
    '量子營運長': ['量子營運長', 'quantum chief operating officer'],
    '量子財務長': ['量子財務長', 'quantum chief financial officer'],
    '量子人資長': ['量子人資長', 'quantum chief human resources officer'],
    '量子行銷長': ['量子行銷長', 'quantum chief marketing officer'],
    '量子業務長': ['量子業務長', 'quantum chief sales officer'],
    '量子法務長': ['量子法務長', 'quantum chief legal officer'],
    '量子公關長': ['量子公關長', 'quantum chief public relations officer'],
    '量子永續長': ['量子永續長', 'quantum chief sustainability officer'],
    '量子創新長': ['量子創新長', 'quantum chief innovation officer'],
    '量子數位長': ['量子數位長', 'quantum chief digital officer'],
    '量子轉型長': ['量子轉型長', 'quantum chief transformation officer'],
    '量子策略長': ['量子策略長', 'quantum chief strategy officer'],
    '量子顧問長': ['量子顧問長', 'quantum chief advisor'],
    '量子總經理': ['量子總經理', 'quantum general manager'],
    '量子副總經理': ['量子副總經理', 'quantum deputy general manager'],
    '量子協理': ['量子協理', 'quantum assistant manager'],
    '量子經理': ['量子經理', 'quantum manager'],
    '量子副理': ['量子副理', 'quantum deputy manager'],
    '量子主任': ['量子主任', 'quantum director'],
    '量子組長': ['量子組長', 'quantum team leader'],
    '量子課長': ['量子課長', 'quantum section chief'],
    '量子股長': ['量子股長', 'quantum unit chief'],
    '量子專員': ['量子專員', 'quantum specialist'],
    '量子助理': ['量子助理', 'quantum assistant'],
    '量子實習生': ['量子實習生', 'quantum intern'],
    '量子工讀生': ['量子工讀生', 'quantum part-time worker'],
    '量子兼職': ['量子兼職', 'quantum part-time'],
    '量子全職': ['量子全職', 'quantum full-time'],
    '量子自由工作者': ['量子自由工作者', 'quantum freelancer'],
    '量子接案者': ['量子接案者', 'quantum contractor'],
    '量子創業家': ['量子創業家', 'quantum entrepreneur'],
    '量子投資人': ['量子投資人', 'quantum investor'],
    '量子股東': ['量子股東', 'quantum shareholder'],
    '量子董事': ['量子董事', 'quantum director'],
    '量子監事': ['量子監事', 'quantum supervisor'],
    '量子顧問': ['量子顧問', 'quantum consultant'],
    '量子委員': ['量子委員', 'quantum committee member'],
    '量子代表': ['量子代表', 'quantum representative'],
    '量子大使': ['量子大使', 'quantum ambassador'],
    '量子特使': ['量子特使', 'quantum special envoy'],
    '量子專員': ['量子專員', 'quantum specialist'],
    '量子專案': ['量子專案', 'quantum project'],
    '量子計畫': ['量子計畫', 'quantum plan'],
    '量子專案經理': ['量子專案經理', 'quantum project manager'],
    '量子產品經理': ['量子產品經理', 'quantum product manager'],
    '量子專案助理': ['量子專案助理', 'quantum project assistant'],
    '量子產品助理': ['量子產品助理', 'quantum product assistant'],
    '量子業務助理': ['量子業務助理', 'quantum sales assistant'],
    '量子行政助理': ['量子行政助理', 'quantum administrative assistant'],
    '量子人資助理': ['量子人資助理', 'quantum HR assistant'],
    '量子財務助理': ['量子財務助理', 'quantum finance assistant'],
    '量子會計助理': ['量子會計助理', 'quantum accounting assistant'],
    '量子法務助理': ['量子法務助理', 'quantum legal assistant'],
    '量子公關助理': ['量子公關助理', 'quantum PR assistant'],
    '量子行銷助理': ['量子行銷助理', 'quantum marketing assistant'],
    '量子企劃助理': ['量子企劃助理', 'quantum planning assistant'],
    '量子設計助理': ['量子設計助理', 'quantum design assistant'],
    '量子工程助理': ['量子工程助理', 'quantum engineering assistant'],
    '量子技術助理': ['量子技術助理', 'quantum technical assistant'],
    '量子研究助理': ['量子研究助理', 'quantum research assistant'],
    '量子教學助理': ['量子教學助理', 'quantum teaching assistant'],
    '量子研究員': ['量子研究員', 'quantum researcher'],
    '量子助理研究員': ['量子助理研究員', 'quantum assistant researcher'],
    '量子副研究員': ['量子副研究員', 'quantum associate researcher'],
    '量子研究員': ['量子研究員', 'quantum researcher'],
    '量子資深研究員': ['量子資深研究員', 'quantum senior researcher'],
    '量子首席研究員': ['量子首席研究員', 'quantum principal researcher'],
    '量子研究總監': ['量子研究總監', 'quantum research director'],
    '量子研究長': ['量子研究長', 'quantum chief research officer'],
    '量子研發長': ['量子研發長', 'quantum chief R&D officer'],
    '量子研發經理': ['量子研發經理', 'quantum R&D manager'],
    '量子研發工程師': ['量子研發工程師', 'quantum R&D engineer'],
    '量子研發助理': ['量子研發助理', 'quantum R&D assistant'],
    '量子研發專員': ['量子研發專員', 'quantum R&D specialist'],
    '量子研發主管': ['量子研發主管', 'quantum R&D supervisor'],
    '量子研發總監': ['量子研發總監', 'quantum R&D director'],
    '量子研發副總': ['量子研發副總', 'quantum R&D vice president'],
    '量子研發總經理': ['量子研發總經理', 'quantum R&D general manager'],
    '量子研發長': ['量子研發長', 'quantum chief R&D officer'],
    '量子創新長': ['量子創新長', 'quantum chief innovation officer'],
    '量子創新經理': ['量子創新經理', 'quantum innovation manager'],
    '量子創新工程師': ['量子創新工程師', 'quantum innovation engineer'],
    '量子創新助理': ['量子創新助理', 'quantum innovation assistant'],
    '量子創新專員': ['量子創新專員', 'quantum innovation specialist'],
    '量子創新主管': ['量子創新主管', 'quantum innovation supervisor'],
    '量子創新總監': ['量子創新總監', 'quantum innovation director'],
    '量子創新副總': ['量子創新副總', 'quantum innovation vice president'],
    '量子創新總經理': ['量子創新總經理', 'quantum innovation general manager'],
    '量子創新長': ['量子創新長', 'quantum chief innovation officer'],
    '量子數位長': ['量子數位長', 'quantum chief digital officer'],
    '量子數位經理': ['量子數位經理', 'quantum digital manager'],
    '量子數位工程師': ['量子數位工程師', 'quantum digital engineer'],
    '量子數位助理': ['量子數位助理', 'quantum digital assistant'],
    '量子數位專員': ['量子數位專員', 'quantum digital specialist'],
    '量子數位主管': ['量子數位主管', 'quantum digital supervisor'],
    '量子數位總監': ['量子數位總監', 'quantum digital director'],
    '量子數位副總': ['量子數位副總', 'quantum digital vice president'],
    '量子數位總經理': ['量子數位總經理', 'quantum digital general manager'],
    '量子數位長': ['量子數位長', 'quantum chief digital officer'],
    '量子轉型長': ['量子轉型長', 'quantum chief transformation officer'],
    '量子轉型經理': ['量子轉型經理', 'quantum transformation manager'],
    '量子轉型工程師': ['量子轉型工程師', 'quantum transformation engineer'],
    '量子轉型助理': ['量子轉型助理', 'quantum transformation assistant'],
    '量子轉型專員': ['量子轉型專員', 'quantum transformation specialist'],
    '量子轉型主管': ['量子轉型主管', 'quantum transformation supervisor'],
    '量子轉型總監': ['量子轉型總監', 'quantum transformation director'],
    '量子轉型副總': ['量子轉型副總', 'quantum transformation vice president'],
    '量子轉型總經理': ['量子轉型總經理', 'quantum transformation general manager'],
    '量子轉型長': ['量子轉型長', 'quantum chief transformation officer'],
    '量子策略長': ['量子策略長', 'quantum chief strategy officer'],
    '量子策略經理': ['量子策略經理', 'quantum strategy manager'],
    '量子策略工程師': ['量子策略工程師', 'quantum strategy engineer'],
    '量子策略助理': ['量子策略助理', 'quantum strategy assistant'],
    '量子策略專員': ['量子策略專員', 'quantum strategy specialist'],
    '量子策略主管': ['量子策略主管', 'quantum strategy supervisor'],
    '量子策略總監': ['量子策略總監', 'quantum strategy director'],
    '量子策略副總': ['量子策略副總', 'quantum strategy vice president'],
    '量子策略總經理': ['量子策略總經理', 'quantum strategy general manager'],
    '量子策略長': ['量子策略長', 'quantum chief strategy officer'],
    '量子顧問長': ['量子顧問長', 'quantum chief advisor'],
    '量子顧問經理': ['量子顧問經理', 'quantum advisor manager'],
    '量子顧問工程師': ['量子顧問工程師', 'quantum advisor engineer'],
    '量子顧問助理': ['量子顧問助理', 'quantum advisor assistant'],
    '量子顧問專員': ['量子顧問專員', 'quantum advisor specialist'],
    '量子顧問主管': ['量子顧問主管', 'quantum advisor supervisor'],
    '量子顧問總監': ['量子顧問總監', 'quantum advisor director'],
    '量子顧問副總': ['量子顧問副總', 'quantum advisor vice president'],
    '量子顧問總經理': ['量子顧問總經理', 'quantum advisor general manager'],
    '量子顧問長': ['量子顧問長', 'quantum chief advisor']
  };
  
  // 檢查創意職業
  for (const [profession, keywords] of Object.entries(creativeProfessions)) {
    for (const keyword of keywords) {
      if (lowerText.includes(keyword.toLowerCase())) {
        return profession;
      }
    }
  }

  // 如果沒有找到明確的職業，檢查一些常見的表達方式
  const commonPatterns = [
    { pattern: /想當(.+)/, group: 1 },
    { pattern: /要當(.+)/, group: 1 },
    { pattern: /成為(.+)/, group: 1 },
    { pattern: /做(.+)/, group: 1 },
    { pattern: /當(.+)/, group: 1 }
  ];

  for (const { pattern, group } of commonPatterns) {
    const match = text.match(pattern);
    if (match) {
      const potentialProfession = match[group].trim();
      // 檢查提取的職業是否在合法列表中
      for (const [profession, keywords] of Object.entries(professionKeywords)) {
        for (const keyword of keywords) {
          if (potentialProfession.includes(keyword) || keyword.includes(potentialProfession)) {
            return profession;
          }
        }
      }
    }
  }

  return '無職業';
}

// 合法職業列表
const VALID_PROFESSIONS = [
  '醫生', '護士', '教師', '律師', '工程師', '設計師', '會計師', '建築師',
  '警察', '消防員', '軍人', '飛行員', '船長', '司機', '廚師', '服務員',
  '銷售員', '經理', '主管', '老闆', '企業家', '科學家', '研究員', '作家',
  '記者', '攝影師', '藝術家', '音樂家', '演員', '導演', '主持人', '主播',
  '運動員', '教練', '營養師', '心理師', '社工', '翻譯', '導遊', '導師',
  '教授', '學者', '專家', '顧問', '分析師', '程式設計師', '系統管理員',
  '網路工程師', '資料科學家', '人工智慧工程師', '機器學習工程師',
  '產品經理', '專案經理', '人力資源', '行政助理', '秘書', '助理',
  '技術員', '技師', '維修員', '清潔員', '保全', '警衛', '園丁', '農夫',
  '漁夫', '礦工', '工人', '技工', '電工', '水電工', '木工', '油漆工',
  '泥水工', '鐵工', '焊接工', '機械工', '汽車技師', '機車技師',
  '美容師', '理髮師', '化妝師', '造型師', '服裝設計師', '珠寶設計師',
  '室內設計師', '景觀設計師', '平面設計師', '網頁設計師', 'UI設計師',
  'UX設計師', '遊戲設計師', '動畫師', '特效師', '剪輯師', '音效師',
  '調音師', '錄音師', '混音師', '製作人', '編劇', '製片', '場記',
  '燈光師', '攝影助理', '化妝助理', '服裝助理', '道具師', '佈景師',
  '特效化妝師', '替身演員', '配音員', '聲優', '模特兒', '舞者',
  '歌手', '樂手', '指揮家', '作曲家', '編曲家', '音樂製作人',
  '錄音工程師', '混音工程師', '母帶工程師', '音響師', '調音師',
  '樂器技師', '鋼琴調音師', '小提琴製琴師', '吉他製琴師',
  '鼓手', '貝斯手', '吉他手', '鍵盤手', '主唱', '和聲', '合唱團',
  '管弦樂團', '交響樂團', '室內樂團', '爵士樂團', '搖滾樂團',
  '流行樂團', '民謠樂團', '古典樂團', '電子樂團', '嘻哈樂團',
  '饒舌歌手', 'DJ', 'MC', '舞者', '編舞家', '舞蹈老師', '瑜珈老師',
  '健身教練', '游泳教練', '網球教練', '籃球教練', '足球教練',
  '棒球教練', '排球教練', '羽球教練', '桌球教練', '高爾夫教練',
  '滑雪教練', '衝浪教練', '潛水教練', '攀岩教練', '登山嚮導',
  '旅遊領隊', '導遊', '解說員', '博物館員', '圖書館員', '檔案管理員',
  '資料管理員', '系統管理員', '網路管理員', '資料庫管理員',
  '伺服器管理員', '安全工程師', '資安工程師', '網路安全工程師',
  '滲透測試工程師', '資安顧問', '資安分析師', '資安管理師',
  '資安稽核師', '資安法規專家', '資安教育訓練師', '資安事件處理師',
  '資安應變工程師', '資安復原工程師', '資安風險管理師',
  '資安政策制定師', '資安標準制定師', '資安認證工程師',
  '資安合規工程師', '資安治理專家', '資安策略顧問', '資安總監',
  '資安長', '資訊長', '技術長', '營運長', '財務長', '人資長',
  '行銷長', '業務長', '法務長', '公關長', '永續長', '創新長',
  '數位長', '轉型長', '策略長', '顧問長', '總經理', '副總經理',
  '協理', '經理', '副理', '主任', '組長', '課長', '股長', '專員',
  '助理', '實習生', '工讀生', '兼職', '全職', '自由工作者',
  '接案者', '創業家', '投資人', '股東', '董事', '監事', '顧問',
  '委員', '代表', '大使', '特使', '專員', '專案', '計畫', '專案經理',
  '產品經理', '專案助理', '產品助理', '業務助理', '行政助理',
  '人資助理', '財務助理', '會計助理', '法務助理', '公關助理',
  '行銷助理', '企劃助理', '設計助理', '工程助理', '技術助理',
  '研究助理', '教學助理', '研究員', '助理研究員', '副研究員',
  '研究員', '資深研究員', '首席研究員', '研究總監', '研究長',
  '研發長', '研發經理', '研發工程師', '研發助理', '研發專員',
  '研發主管', '研發總監', '研發副總', '研發總經理', '研發長',
  '創新長', '創新經理', '創新工程師', '創新助理', '創新專員',
  '創新主管', '創新總監', '創新副總', '創新總經理', '創新長',
  '數位長', '數位經理', '數位工程師', '數位助理', '數位專員',
  '數位主管', '數位總監', '數位副總', '數位總經理', '數位長',
  '轉型長', '轉型經理', '轉型工程師', '轉型助理', '轉型專員',
  '轉型主管', '轉型總監', '轉型副總', '轉型總經理', '轉型長',
  '策略長', '策略經理', '策略工程師', '策略助理', '策略專員',
  '策略主管', '策略總監', '策略副總', '策略總經理', '策略長',
  '顧問長', '顧問經理', '顧問工程師', '顧問助理', '顧問專員',
  '顧問主管', '顧問總監', '顧問副總', '顧問總經理', '顧問長'
];

// 職業驗證 - 改為只排除非法職業
router.post('/validate', async (req, res) => {
  try {
    const { text, sessionId } = req.body;

    if (!text) {
      return res.status(400).json({ error: '沒有提供文字內容' });
    }

    // 使用本地規則引擎進行職業提取和驗證
    const extractedProfession = extractProfessionFromText(text);

    // 檢查結果
    if (extractedProfession === '無職業') {
      return res.json({
        valid: false,
        message: '文字中沒有提到職業',
        profession: null
      });
    }

    if (extractedProfession === '職業不合法') {
      return res.json({
        valid: false,
        message: '提到的職業不合法或不合理',
        profession: null
      });
    }

    // 定義非法職業列表（只排除真正非法的職業）
    const ILLEGAL_PROFESSIONS = [
      '殺手', '殺人犯', '強盜', '小偷', '詐騙犯', '毒販', '黑幫', '恐怖分子',
      'killer', 'murderer', 'robber', 'thief', 'fraudster', 'drug dealer', 'gangster', 'terrorist',
      '殺人', '搶劫', '偷竊', '詐騙', '販毒', '黑社會', '恐怖主義',
      'murder', 'robbery', 'theft', 'fraud', 'drug trafficking', 'organized crime', 'terrorism'
    ];

    // 檢查是否為非法職業
    const isIllegalProfession = ILLEGAL_PROFESSIONS.some(illegal => 
      extractedProfession.toLowerCase().includes(illegal.toLowerCase()) ||
      illegal.toLowerCase().includes(extractedProfession.toLowerCase())
    );

    if (isIllegalProfession) {
      return res.json({
        valid: false,
        message: '提到的職業不合法',
        profession: extractedProfession
      });
    }

    // 更新使用者資料
    if (sessionId) {
      let user = await User.findOne({ sessionId });
      if (user) {
        user.profession = extractedProfession;
        user.status = 'photo';
        await user.save();
      }
    }

    res.json({
      valid: true,
      message: '職業驗證成功',
      profession: extractedProfession
    });

  } catch (error) {
    console.error('職業驗證錯誤:', error);
    res.status(500).json({
      error: '職業驗證失敗',
      details: error.message
    });
  }
});

// 獲取職業資訊
router.get('/info/:sessionId', async (req, res) => {
  try {
    const user = await User.findOne({ sessionId: req.params.sessionId });
    if (!user) {
      return res.status(404).json({ error: '找不到該會話' });
    }

    res.json({
      profession: user.profession,
      status: user.status
    });
  } catch (error) {
    res.status(500).json({ error: '獲取職業資訊失敗' });
  }
});

module.exports = router;
